apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: {{ .Release.Name }}-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  hostPath:
    path: {{ .Values.persistentVolume.path_on_host }}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
