replicaCount: 1

image:
  repository: avashskya/go-leaf
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  periodSeconds: 10
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  periodSeconds: 10
  failureThreshold: 3
  successThreshold: 2
  timeoutSeconds: 1
  initialDelaySeconds: 5

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

persistentVolume:
  capacity: 10Gi
  path_on_host: /appdata
  path_in_pod: /logs
