replicaCount: 1

image:
  repository: avashskya/go-leaf
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 8080

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  httpGet:
    path: /health
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

