name: CI/CD

on:
  push:
    branches: [ staging, main ]
#  pull_request:
#    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Application
        run: |
          go mod tidy
          go build -o app

      - name: Docker Build & Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.ref_name }}-${{ github.event.head_commit.message }}
        run: |
          docker build -t avashskya/go-leaf:$IMAGE_TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push avashskya/go-leaf:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      EKS_CLUSTER_NAME: go-leaf

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config for production
        if: ${{ github.ref_name == 'main' }}
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}-prod --region ${{ env.AWS_REGION }}

      - name: Update kube config for staging
        if: ${{ github.ref_name == 'staging' }}
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}-staging --region ${{ env.AWS_REGION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to EKS
        env:
          IMAGE_TAG: ${{ github.ref_name}}-${{ github.event.head_commit.message }}
        run: |
          helm upgrade --install go-leaf ./go-leaf \
            --namespace default \
            --set image.tag=$IMAGE_TAG \
            --wait --timeout 5m
